---
- name: Delete Longhorn Ingress
  shell: |
    cat <<EOF | kubectl --context {{ cluster }} delete -f -
    {{ lookup('template', 'longhorn-ingress.yml') }}
    EOF

- name: Delete Longhorn operator
  command: "kubectl --context {{ cluster }} create -f {{ longhorn_uninstall_manifest }}"

- name: Wait for Longhorn uninstall
  command: "kubectl --context {{ cluster }} get job/longhorn-uninstall -n longhorn-system -w"
