version: "3"

services:
  postgres:
    container_name: postgres
    restart: always
    image: {{ postgres_image }}
    network_mode: host
    volumes:
      - "{{ postgres_dir }}/data:/var/lib/postgresql/data"
      - "{{ postgres_dir }}/backup:/backup"
      - "{{ postgres_dir }}/pg_backup.sh:/pg_backup.sh"
    environment:
      - POSTGRES_USER=${POSTGRES_SUPERUSER_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_SUPERUSER_PASS}
      - POSTGRES_DB=${POSTGRES_SUPERUSER_DB}
      - PGDATA=/var/lib/postgresql/data
