- name: Cloudnative PG setup
  tags: cloudnative-pg-up
  include_tasks:
    file: up.yml
    apply:
      tags: cloudnative-pg-up
  when: '"cloudnative-pg-up" in ansible_run_tags'

- name: Cloudnative PG teardown
  tags: cloudnative-pg-down
  include_tasks:
    file: down.yml
    apply:
      tags: cloudnative-pg-down
  when: '"cloudnative-pg-down" in ansible_run_tags'

- name: Cloudnative PG on-demand backup
  tags: cloudnative-pg-backup
  include_tasks:
    file: backup.yml
    apply:
      tags: cloudnative-pg-backup
  when: '"cloudnative-pg-backup" in ansible_run_tags'
