- name: Create ghost directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ghost_dir }}"
    - "{{ ghost_dir }}/content"

- name: Create config.production.json file
  template:
    src: config.production.json.j2
    dest: "{{ ghost_dir }}/config.production.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ ghost_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Pull image
  docker_image:
    name: "{{ ghost_image }}"
    source: pull

- name: docker-compose down (just in case)
  docker_compose:
    project_name: ghost
    project_src: "{{ ghost_dir }}"
    state: absent
    remove_orphans: yes

- name: docker-compose up
  docker_compose:
    project_name: ghost
    project_src: "{{ ghost_dir }}"
    recreate: always
