version: "3"

services:
  ghost:
    container_name: ghost
    image: {{ ghost_image }}
    restart: always
    volumes:
      - "{{ ghost_dir }}/config.production.json:/var/lib/ghost/config.production.json"
      - "{{ ghost_dir }}/content:/var/lib/ghost/content"
    network_mode: "host"
    environment:
      - NODE_ENV=production
  mc:
    container_name: mc
    image: {{ ghost_mc_image }}
    restart: always
    command: mirror --overwrite --remove --md5 --watch /content/ minio/{{ ghost_minio_bucket }}/{{ cluster }}/
    volumes:
      - "{{ ghost_dir }}/mc.config.json:/root/.mc/config.json"
      - "{{ ghost_dir }}/content:/content"
