---
- name: Set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: Install common packages
  include_tasks: packages.yml

- name: Security setup
  include_tasks: security.yml

