---
- name: docker-compose down
  docker_compose:
    project_name: postgres
    project_src: "{{ postgres_dir }}"
    state: absent
    remove_orphans: yes

- name: Delete postgres directory
  file:
    path: "{{ postgres_dir }}"
    state: directory
