---
- name: docker-compose down
  docker_compose:
    project_name: postgres
    project_src: "{{ postgres_dir }}"
    state: absent
    remove_orphans: yes
  when: color == "green" or color == "blue"
  failed_when: false

- name: Delete postgres directory
  become: true
  file:
    path: "{{ postgres_dir }}"
    state: absent
  when: color == "green" or color == "blue"
