- name: Postgres setup
  tags: postgres-up
  include_tasks:
    file: up.yml
    apply:
      tags: postgres-up
  when: '"postgres-up" in ansible_run_tags'

- name: Postgres teardown
  tags: postgres-down
  include_tasks:
    file: down.yml
    apply:
      tags: postgres-down
  when: '"postgres-down" in ansible_run_tags'

- name: Postgres on-demand backup
  tags: postgres-backup
  include_tasks:
    file: backup.yml
    apply:
      tags: postgres-backup
  when: '"postgres-backup" in ansible_run_tags' 