- name: Get the master node ip
  set_fact:
    master_ip: "{{ hostvars[groups['green'][0]]['ansible_host'] }}"

- name: Get the replica node ip
  set_fact:
    replica_ip: "{{ hostvars[groups['blue'][0]]['ansible_host'] }}"

- name: Setup master
  include_tasks:
    file: master.yml
  when: color == "green"

- name: Setup replica
  include_tasks:
    file: replica.yml
  when: color == "blue"
