project: project
domain: "{{ project }}.test"
cluster: vm

packages:
  - acl # Needed for becoming non root user (i.e. postgres)
  - curl
  - ntp
  # Longhorn requirements
  - nfs-common
  - open-iscsi

services:
  - ntp
